// <auto-generated />
namespace EcoHand.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregando_campos_a_los_modelos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregando_campos_a_los_modelos));
        
        string IMigrationMetadata.Id
        {
            get { return "201907231919314_agregando_campos_a_los_modelos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
